-- ============================================================
-- R__create_views.sql
-- Repeatable スクリプト: ビューの作成・更新
-- 変更があるたびに再実行されます
-- ============================================================

-- ゲーム一覧ビュー（CORE レイヤ）
CREATE OR REPLACE VIEW CORE_ZELDA.V_GAMES AS
SELECT 
  GAME_ID,
  GAME_NAME,
  DEVELOPER,
  PUBLISHER,
  RELEASED_DATE,
  CREATED_AT
FROM CORE_ZELDA.DIM_GAME
ORDER BY RELEASED_DATE;

-- 開発会社別ゲーム数サマリ（MART レイヤ）
CREATE OR REPLACE VIEW MART_ZELDA.V_GAMES_BY_DEVELOPER AS
SELECT 
  DEVELOPER,
  COUNT(*) AS GAME_COUNT,
  MIN(RELEASED_DATE) AS FIRST_RELEASE,
  MAX(RELEASED_DATE) AS LATEST_RELEASE
FROM CORE_ZELDA.DIM_GAME
GROUP BY DEVELOPER
ORDER BY GAME_COUNT DESC;

-- 発売元別ゲーム数サマリ（MART レイヤ）
CREATE OR REPLACE VIEW MART_ZELDA.V_GAMES_BY_PUBLISHER AS
SELECT 
  PUBLISHER,
  COUNT(*) AS GAME_COUNT,
  MIN(RELEASED_DATE) AS FIRST_RELEASE,
  MAX(RELEASED_DATE) AS LATEST_RELEASE
FROM CORE_ZELDA.DIM_GAME
GROUP BY PUBLISHER
ORDER BY GAME_COUNT DESC;

-- 10年代別ゲーム数サマリ（MART レイヤ）
-- ★ テストシナリオで追加したビュー
CREATE OR REPLACE VIEW MART_ZELDA.V_GAMES_BY_DECADE AS
SELECT 
  CONCAT(FLOOR(CAST(REGEXP_SUBSTR(RELEASED_DATE, '[0-9]{4}') AS INT) / 10) * 10, 's') AS DECADE,
  COUNT(*) AS GAME_COUNT
FROM CORE_ZELDA.DIM_GAME
WHERE REGEXP_SUBSTR(RELEASED_DATE, '[0-9]{4}') IS NOT NULL
GROUP BY FLOOR(CAST(REGEXP_SUBSTR(RELEASED_DATE, '[0-9]{4}') AS INT) / 10) * 10
ORDER BY DECADE;

