-- ============================================================
-- V1.3.0__create_dim_game.sql
-- DIM_GAME テーブルを作成（ゲームマスタ）
-- ============================================================

CREATE TABLE IF NOT EXISTS CORE_ZELDA.DIM_GAME (
  GAME_ID VARCHAR(50) PRIMARY KEY,
  GAME_NAME VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(10000),
  DEVELOPER VARCHAR(100),
  PUBLISHER VARCHAR(100),
  RELEASED_DATE VARCHAR(50),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- テーブルコメント
COMMENT ON TABLE CORE_ZELDA.DIM_GAME IS 'ゲームマスタテーブル';
COMMENT ON COLUMN CORE_ZELDA.DIM_GAME.GAME_ID IS 'ゲームID（主キー）';
COMMENT ON COLUMN CORE_ZELDA.DIM_GAME.GAME_NAME IS 'ゲーム名';
COMMENT ON COLUMN CORE_ZELDA.DIM_GAME.DESCRIPTION IS '説明文';
COMMENT ON COLUMN CORE_ZELDA.DIM_GAME.DEVELOPER IS '開発会社';
COMMENT ON COLUMN CORE_ZELDA.DIM_GAME.PUBLISHER IS '発売元';
COMMENT ON COLUMN CORE_ZELDA.DIM_GAME.RELEASED_DATE IS '発売日';
